---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-ddns
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: cronjob
      cronjob:
        concurrencyPolicy: Forbid
        schedule: "@hourly"
    restartPolicy: OnFailure
    image:
      repository: ghcr.io/onedr0p/kubernetes-kubectl
      tag: 1.27.2@sha256:a5ca5e954b5c03f28a51f4fe82a7814b7c8a6cb44d1c3eb26ddcd2b14c03ef53
    command: ["/bin/bash", "/app/cloudflare-ddns.sh"]
    envFrom:
      - secretRef:
          name: cloudflare-ddns-secret
    service:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        type: configMap
        name: cloudflare-ddns-configmap
        subPath: cloudflare-ddns.sh
        mountPath: /app/cloudflare-ddns.sh
        defaultMode: 0775
        readOnly: true
