---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-pvc-longhorn
  namespace: security
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
