---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-weave-gitops-secret
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: test-weave-gitops-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: weave-gitops-admin
        property: password
