---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-mail-relay
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-onepassword
  path: ./kubernetes/apps/networking/mail-relay/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: mail-relay
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m
