---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sendgrid-apikey-secret
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sendgrid-apikey-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: sendgrid-apikey
        property: password
