---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app mail-relay
  namespace: networking
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 15m
  install:
    disableWait: true
    remediation:
      retries: 100
  upgrade:
    remediation:
      retries: 100
  values:
    env:
      - name: SMTP_SERVER
        value: smtp.sendgrid.net
      - name: OVERWRITE_FROM
        value: "${SECRET_SENDGRID_USER_SMTP_RELAY}"
      - name: SMTP_USERNAME
        value: apikey
      - name: SMTP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sendgrid-apikey-secret
            key: password
      - name: SERVER_HOSTNAME
        value: "${SECRET_SMTP_DOMAIN}"
    image:
      repository: docker.io/juanluisbaptiste/postfix
      tag: 1.7.1
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${SVC_SMTP_RELAY_ADDR}
        externalIPs:
          - "${SVC_SMTP_RELAY_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: &port 25
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        memory: 256Mi
