---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-ip
  namespace: networking
spec:
  ipAddressPools:
    - default-pool
    - dns-pool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: networking
spec:
  addresses:
    - "${METALLB_LB_RANGE}"
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dns-pool
  namespace: networking
spec:
  addresses:
    - 192.168.128.3/32
  autoAssign: false
