---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    serviceAccount:
      name: tailscale

    image:
      repository: ghcr.io/tailscale/tailscale
      tag: v1.40.0
    env:
      TZ: "America/New_York"
      TS_KUBE_SECRET: "tailscale-auth"
      SA_NAME: tailscale
      TS_USERSPACE: "true"
      TS_ROUTES: "192.168.128.0/20"
      TS_EXTRA_ARGS: "--advertise-exit-node"
    envFrom:
      - secretRef:
          name: tailscale-auth

    service:
      main:
        enabled: false
        # ports:
        #   http:
        #     port: 45387

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000

    ingress:
      main:
        enabled: false
