---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap-secrets
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lldap-secrets
    creationPolicy: Owner
  data:
    - secretKey: LLDAP_LDAP_BASE_DN
      remoteRef:
        key: lldap-admin
        property: base_dn
    - secretKey: LLDAP_LDAP_USER_PASS
      remoteRef:
        key: lldap-admin
        property: password
    - secretKey: LLDAP_JWT_SECRET
      remoteRef:
        key: lldap-admin
        property: jwt-secret
