---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap-secret
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
    - secretKey: lldap-userpass
      remoteRef:
        key: lldap-admin
        property: password
    - secretKey: lldap-jwt-secret
      remoteRef:
        key: lldap-jwt
        property: credential
