---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap-secrets
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lldap-secrets
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: lldap-admin
        property: password
    - secretKey: jwt-secret
      remoteRef:
        key: lldap-admin
        property: jwt-secret
