---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app lldap
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/lldap/lldap
      tag: v0.4.3
    env:
      TZ: "${TIMEZONE}"
    envFrom:
      - secretRef:
          name: lldap-secrets
    service:
      main:
        ports:
          http:
            port: 3890
          web:
            enabled: true
            protocol: TCP
            port: &http-port 17170
    ingress:
      main:
        enabled: true
        primary: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: folder-key-network-outline
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.244.0.0/16,10.10.0.0/24,10.0.8.0/24,192.168.10.0/24,192.168.200.0/24
        hosts:
          - host: &host "ldap.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *http-port
        tls:
          - hosts:
              - *host
            secretName: "${SECRET_DOMAIN/./-}-production-tls"
    persistence:
      data:
        enabled: true
        existingClaim: lldap-pvc-longhorn
        mountPath: /data
    # resources:
    #   requests:
    #     cpu: 10m
    #     memory: 100Mi
    #   limits:
    #     memory: 500Mi
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
